#!/usr/bin/env zsh

uri_unescape() {
    perl -e 'use URI::Escape; print uri_unescape($ARGV[0])' "$1"
}

# SITEMAP
cat <<EOF > ../sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://dset0x.github.io/</loc>
        <lastmod>$(date +%F)</lastmod>
        <changefreq>10</changefreq>
        <priority>0.5</priority>
    </url>
EOF

# FEED
cat <<EOF > ../feed.xml
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
xmlns:content="http://purl.org/rss/1.0/modules/content/"
xmlns:wfw="http://wellformedweb.org/CommentAPI/"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:atom="http://www.w3.org/2005/Atom"
xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
xmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:media="http://search.yahoo.com/mrss/"
>

<channel>
  <title>When software gets in the way</title>
  <link>https://dset0x.github.io</link>
  <description>A collection of workarounds and patches that I've written to deal with all sorts of software and life problems.</description>

	<atom:link href="https://dset0x.github.io/feed.xml" rel="self" type="application/rss+xml" />
	<lastBuildDate>Thu, 09 Feb 2017 15:49:48 +0000</lastBuildDate>
	<language>en</language>
	<sy:updatePeriod>daily</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>

EOF

for j in $( ls -t *.txt ); do
    [[ "$j" == index.txt ]] && continue
    i="${j%.*}"

    title=$(head -n1 "$i".txt)
    keys=$(cat "$i".txt | head -n2 | tail -n1)
    preview=$(tail -n +3 $i.txt | grep '^\S' | paste -sd " " - | sed 's/<URL:.*:\(.*\)>/\1/g' | cut -d' ' -f 1-70)

    # HTML
    ./header.sh "$title - When software gets in the way" "$preview" "$keys" > ../"$i".html
    txt2html --extract --prebegin 1 --prewhite 4 --titlefirst --underline_delimiter '' --bold_delimiter '' --italic_delimiter '' --links_dictionaries dict.dict =(tail -n +3 "$i".txt) >> ../"$i".html
    cat footer.html >> ../"$i".html


    # INDEX
    echo -e "<div><h2 style=\"display: inline;\"><a href=\"/$i.html\">$(head -1 "$i.txt")</a></h2> <div class=\"preview\">$preview...</div></div><br>" >> index.tmp

    # SITEMAP
    cat <<EOF >> ../sitemap.xml
    <url>
        <loc>https://dset0x.github.io/$i.html</loc>
        <lastmod>$(stat -c %y "$i.txt" | cut -d' ' -f1)</lastmod>
        <changefreq>10</changefreq>
        <priority>0.5</priority>
    </url>
EOF

    # FEED
    cat <<EOF >> ../feed.xml
  <item>
    <title>$(head -1 "$i.txt")</title>
    <link>https://dset0x.github.io/$i.html</link>
    <description>$preview</description>
    <pubDate>$(date -R --date="$(stat -c %y "$i.txt")")</pubDate>
  </item>
EOF

done

echo '</urlset>' >> ../sitemap.xml

cat <<EOF >> ../feed.xml
</channel>

</rss>
EOF

# INDEX
./header.sh "When software gets in the way" "A collection of workarounds and patches that I've written to deal with all sorts of software and life problems." "hacks,patches,perl,python,linux,terminal,blog" > ../index.html
txt2html --extract --prebegin 1 --prewhite 4 --titlefirst --underline_delimiter '' --bold_delimiter '' --italic_delimiter '' --short_line_length 80 --links_dictionaries dict.dict --append_file index.tmp index.txt >> ../index.html
cat footer.html >> ../index.html


rm index.tmp
