#!/usr/bin/env bash

##############################################################################
site_title='When software gets in the way'
site_desc='A collection of workarounds and patches to solve all life''s problems.'
site_keywords="hacks,patches,perl,python,linux,terminal,blog"
domain='https://dset0x.github.io'
# txt2blog="txt2html --extract --prebegin 1 --prewhite 4 --titlefirst \
#   --underline_delimiter '' --bold_delimiter '' --italic_delimiter '' \
#   --links_dictionaries dict.dict"
txtext="md"
txt2blog="markdown"
preview_words=70
# In relation to current dir:
base="../"
sitemap="$base/sitemap.xml"
feed="$base/feed.xml"
extras="overlay"
##############################################################################

esc() { perl -e 'use HTML::Entities; print encode_entities($ARGV[0]);' "$1"; }

# EXTRAS
cp -rf $extras/* "$base"

# INDEX
echo '<h1>Notes</h1>' > index.tmp

# SITEMAP
cat <<EOF > "$sitemap"
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>$domain</loc>
        <lastmod>$(date +%F)</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
EOF

# FEED
wfeed="/$(realpath --relative-to=$base $feed)"
cat <<EOF > "$feed"
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
xmlns:content="http://purl.org/rss/1.0/modules/content/"
xmlns:wfw="http://wellformedweb.org/CommentAPI/"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:atom="http://www.w3.org/2005/Atom"
xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
>
<channel>
  <title>$site_title</title>
  <link>$domain</link>
  <description>$site_desc</description>
	<atom:link href="$domain$wfeed" rel="self" type="application/rss+xml" />
	<language>en</language>
	<sy:updatePeriod>daily</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
EOF

max_date=0
for txt in $(find . -name '*.'"$txtext" -print0 | xargs --null head -n1 | \
  awk -F' ' '/^=/ {f=$2;} /^2/ {print $1, f;}' | sort -r | cut -d' ' -f2); do

    [[ "$txt" == ./index."$txtext" ]] && continue

    # SOURCE
    dir="$(dirname $txt)"
    bname="$(basename $txt)"

    # DEST
    mkdir -p "$base/$dir"
    fname="${bname%.*}"
    html="$base/$dir/$fname.html"

    # WEB
    wpath="/$(realpath --relative-to=$base $base/$dir/$fname.html)"

    # INFO
    date=$(date --date="$(head -1 "$txt" | cut -d' ' -f1)" +%s)
    keywords=$(esc     "$(head -1 "$txt" | cut -d' ' -f2)")
    title=$(esc        "$(head -2 "$txt" | tail -1)")
    preview=$(esc      "$(tail -n +4 "$txt" | grep '^[a-zA-Z]' | paste -sd " " - | \
      perl -pe 's/\[(.*?)\]\(.*?\)|^-*$()|^\* (.*)\s/\1/g' | cut -d' ' -f 1-$preview_words)")..
    [[ $date -gt $max_date ]] && max_date=$date

    typ="article"
    [[ "$dir" == "./pages" ]] && typ="$fname"

    # PAGE
    {
      ./header.sh "$typ" "$title - $site_title" "$title" "$keywords"
      echo '<article>'
      ${txt2blog} < <(tail -n +2 "$txt")
      echo '</article>'
      cat footer.html
    } > "$html"

    # INDEX
    if [[ "$typ" == "article" ]]; then
      cat <<EOF >> index.tmp
      <article>
          <h2><a href="$wpath">$title</a></h2>
          <div class="preview">
              $preview
          </div>
          <div class="cont_box">
              <!--<div class="cont">
                  <a title="Continue reading" href="$wpath">Continue reading</a>
              </div>-->
              <hr>
          </div>
      </article>
EOF
    fi

    # SITEMAP
    cat <<EOF >> "$sitemap"
    <url>
        <loc>$domain$wpath</loc>
        <lastmod>$(date --date="@$date" +%F)</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.7</priority>
    </url>
EOF

    # FEED
    cat <<EOF >> "$feed"
  <item>
    <title>$title</title>
    <link>$domain$wpath</link>
    <description>$preview</description>
    <pubDate>$(date -R --date="@$date")</pubDate>
  </item>
EOF

done


# INDEX
{
  ./header.sh "notes" "$site_title" "$site_desc" "$site_keywords"
  cat index.tmp footer.html
} > "$base/index.html"
rm index.tmp

# SITEMAP
echo '</urlset>' >> "$sitemap"

# FEED
cat <<EOF >> "$feed"
    <lastBuildDate>$(date -R --date="@$max_date")</lastBuildDate>
  </channel>
</rss>
EOF
